This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./kidiplom.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file kidiplom.acn....done (10 entries accepted, 0 rejected).
Sorting entries....done (31 comparisons).
Generating output file kidiplom.acr....done (27 lines written, 0 warnings).
Output written in kidiplom.acr.
Transcript written in kidiplom.alg.
